#!/bin/bash
## Mostly generated by chatgpt

# Check if a filename is provided as an argument
if [ $# -ne 1 ]; then
        echo "Usage: $0 <csv_file>"
            exit 1
fi

csv_file="$1"

# Check if the provided file exists
if [ ! -f "$csv_file" ]; then
        echo "Error: File '$csv_file' not found."
            exit 1
fi

# Read the CSV file and output an ASCII table with the 1st and 5th columns
awk -F',' 'BEGIN {printf "%-20s\t%-20s\n", "Serialization Library", "Highest Achieved Load (1000 packets per second)"} {
    if (NR > 1) {
        printf "%-20s\t%-20s\n", $1, $5 / 1000;
    }
}' "$csv_file"

